# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build the factorial design
#' 
#' Build the factorial design based on the vectors of independent variables.
#' 
#' @param s_prop (numeric vector) Proportions of response shift.
#' @param s_magn (numeric vector) Magnitudes of response shift.
#' @param s_type (numeric vector) Types of response shift (i.e., towards slope, threshold, or both).
#' @param p_type (numeric vector) Types of item parameters (i.e., homogeneous or heterogeneous).
#' @param t_leng (numeric vector) Lengths of the test (i.e., number of items).
#' 
#' @export
#' 
buildDesign <- function(shift_proportions, shift_magnitudes, shift_types, parameters_types, test_lengths) {
    .Call('FypSim_buildDesign', PACKAGE = 'FypSim', shift_proportions, shift_magnitudes, shift_types, parameters_types, test_lengths)
}

#' Apply procedure for a single cell
#' 
#' Perform the calibration and estimation for a single cell. Subsequently, we will use this
#' when we loop through the entire factorial design and for each cell we instantiate the
#' SimulateCell class. We have to also keep an eye on the fact that the entire design
#' in itself will also need to be replicated \code{n} times.
#' 
#' @param population_theta (double) Vector of latent abilities for the population.
#' @param shift_proportion (double) Proportion of response shift.
#' @param shift_magnitude (double) Magnitude of response shift.
#' @param shift_type (int) Type of response shift (i.e., towards slope, threshold, or both).
#' @param parameters_type (int) Type of item parameters (i.e., homogeneous or heterogeneous).
#' @param test_length (int) Lengths of the test (i.e., number of items).
#' 
#' @export
#' 
runCell <- function(population_theta, shift_proportion, shift_magnitude, shift_type, parameters_type, test_length) {
    .Call('FypSim_runCell', PACKAGE = 'FypSim', population_theta, shift_proportion, shift_magnitude, shift_type, parameters_type, test_length)
}

